"""Add payout model for seller earnings

Revision ID: 5822d3a8617c
Revises: b37627451129
Create Date: 2025-10-18 15:18:24.393270

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '5822d3a8617c'
down_revision = 'b37627451129'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payouts',
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('platform_fee_total', sa.Numeric(precision=10, scale=2), nullable=False, comment='Total platform fees from included transactions'),
    sa.Column('transaction_count', sa.Integer(), nullable=False, comment='Number of transactions in this payout'),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'PAID', 'FAILED', name='payout_status'), nullable=False),
    sa.Column('stripe_payout_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_transfer_id', sa.String(length=255), nullable=True),
    sa.Column('bank_account_last4', sa.String(length=4), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], name=op.f('fk_payouts_seller_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payouts'))
    )
    op.create_index('ix_payouts_paid_at', 'payouts', ['paid_at'], unique=False)
    op.create_index('ix_payouts_seller', 'payouts', ['seller_id'], unique=False)
    op.create_index('ix_payouts_status', 'payouts', ['status'], unique=False)
    op.drop_index('ix_conversations_archived', table_name='conversations')
    op.drop_index('ix_conversations_buyer_seller_product', table_name='conversations')
    op.create_foreign_key('fk_conversations_last_message', 'conversations', 'messages', ['last_message_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.drop_index('ix_messages_conversation_created', table_name='messages')
    op.drop_index('ix_messages_is_read', table_name='messages')
    op.drop_index('ix_offers_buyer_created', table_name='offers')
    op.drop_index('ix_offers_seller_created', table_name='offers')
    op.drop_index('ix_offers_status_expires', table_name='offers')
    op.drop_index('idx_products_fulltext_search', table_name='products', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_products_fulltext_search', 'products', [sa.text("to_tsvector('english'::regconfig, (title::text || ' '::text) || COALESCE(description, ''::text))")], unique=False, postgresql_using='gin')
    op.create_index('ix_offers_status_expires', 'offers', ['status', 'expires_at'], unique=False)
    op.create_index('ix_offers_seller_created', 'offers', ['seller_id', 'created_at'], unique=False)
    op.create_index('ix_offers_buyer_created', 'offers', ['buyer_id', 'created_at'], unique=False)
    op.create_index('ix_messages_is_read', 'messages', ['is_read'], unique=False)
    op.create_index('ix_messages_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.drop_constraint('fk_conversations_last_message', 'conversations', type_='foreignkey')
    op.create_index('ix_conversations_buyer_seller_product', 'conversations', ['buyer_id', 'seller_id', 'product_id'], unique=False)
    op.create_index('ix_conversations_archived', 'conversations', ['is_archived_buyer', 'is_archived_seller'], unique=False)
    op.drop_index('ix_payouts_status', table_name='payouts')
    op.drop_index('ix_payouts_seller', table_name='payouts')
    op.drop_index('ix_payouts_paid_at', table_name='payouts')
    op.drop_table('payouts')
    # ### end Alembic commands ###

